
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ifaldzi
 */
public class FramePemesanan extends javax.swing.JFrame {
    private int totalPay = 0;
    private static final int STEAKPRICE = 45000;
    private static final int SPHAGETIPRICE = 37500;
    private static final int PIZZAPRICE = 99000;
    /**
     * Creates new form FramePemesanan
     */
    public FramePemesanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerPanel = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        customerNameField = new javax.swing.JTextField();
        labelAddress = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        labelPhone = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        foodMenuPanel = new javax.swing.JPanel();
        steakCheckBox = new javax.swing.JCheckBox();
        sphagetiCheckBox = new javax.swing.JCheckBox();
        pizzaCheckBox = new javax.swing.JCheckBox();
        totalPanel = new javax.swing.JPanel();
        totalPayLabel = new javax.swing.JLabel();
        addOrderButton = new javax.swing.JButton();
        totalPayTextField = new javax.swing.JTextField();
        dataPenjualanPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTextArea = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pemesanan Makanan");

        customerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Data Customer"));
        customerPanel.setToolTipText("");
        customerPanel.setName(""); // NOI18N

        labelName.setText("Nama:");

        labelAddress.setText("Alamat:");

        labelPhone.setText("No Telp:");

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelName)
                    .addComponent(labelAddress)
                    .addComponent(labelPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phoneField)
                    .addComponent(addressField)
                    .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddress)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPhone)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        foodMenuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pilih Menu"));

        steakCheckBox.setText("Steak (45000)");
        steakCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                steakCheckBoxActionPerformed(evt);
            }
        });

        sphagetiCheckBox.setText("Sphageti (37500)");
        sphagetiCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sphagetiCheckBoxActionPerformed(evt);
            }
        });

        pizzaCheckBox.setText("Pizza (99000)");
        pizzaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout foodMenuPanelLayout = new javax.swing.GroupLayout(foodMenuPanel);
        foodMenuPanel.setLayout(foodMenuPanelLayout);
        foodMenuPanelLayout.setHorizontalGroup(
            foodMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(foodMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(steakCheckBox)
                    .addComponent(sphagetiCheckBox)
                    .addComponent(pizzaCheckBox))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        foodMenuPanelLayout.setVerticalGroup(
            foodMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(steakCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sphagetiCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pizzaCheckBox)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        totalPayLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalPayLabel.setLabelFor(totalPanel);
        totalPayLabel.setText("TOTAL BAYAR");

        addOrderButton.setText("TAMBAH");
        addOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderButtonActionPerformed(evt);
            }
        });

        totalPayTextField.setEditable(false);
        totalPayTextField.setBackground(new java.awt.Color(0, 0, 0));
        totalPayTextField.setForeground(new java.awt.Color(255, 255, 0));
        totalPayTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalPayTextField.setText("0");

        javax.swing.GroupLayout totalPanelLayout = new javax.swing.GroupLayout(totalPanel);
        totalPanel.setLayout(totalPanelLayout);
        totalPanelLayout.setHorizontalGroup(
            totalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addOrderButton))
            .addGroup(totalPanelLayout.createSequentialGroup()
                .addComponent(totalPayLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(totalPayTextField)
        );
        totalPanelLayout.setVerticalGroup(
            totalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPanelLayout.createSequentialGroup()
                .addComponent(totalPayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalPayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(addOrderButton))
        );

        dataPenjualanPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Data Penjualan"));

        dataTextArea.setEditable(false);
        dataTextArea.setColumns(20);
        dataTextArea.setRows(5);
        jScrollPane1.setViewportView(dataTextArea);

        saveButton.setText("Simpan");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load Data");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataPenjualanPanelLayout = new javax.swing.GroupLayout(dataPenjualanPanel);
        dataPenjualanPanel.setLayout(dataPenjualanPanelLayout);
        dataPenjualanPanelLayout.setHorizontalGroup(
            dataPenjualanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPenjualanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPenjualanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addGroup(dataPenjualanPanelLayout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addGap(18, 18, 18)
                        .addComponent(loadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetButton)))
                .addContainerGap())
        );
        dataPenjualanPanelLayout.setVerticalGroup(
            dataPenjualanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPenjualanPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPenjualanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(loadButton)
                    .addComponent(resetButton))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("APLIKASI PEMESANAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataPenjualanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(foodMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(totalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataPenjualanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void steakCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_steakCheckBoxActionPerformed
        if(steakCheckBox.isSelected()){
            totalPay += STEAKPRICE;
        }
        else{
            totalPay -= STEAKPRICE;
        }
        totalPayTextField.setText(String.valueOf(totalPay));
    }//GEN-LAST:event_steakCheckBoxActionPerformed

    private void sphagetiCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sphagetiCheckBoxActionPerformed
        if(sphagetiCheckBox.isSelected()){
            totalPay += SPHAGETIPRICE;
        }
        else{
            totalPay -= SPHAGETIPRICE;
        }
        totalPayTextField.setText(String.valueOf(totalPay));
    }//GEN-LAST:event_sphagetiCheckBoxActionPerformed

    private void pizzaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaCheckBoxActionPerformed
        if(pizzaCheckBox.isSelected()){
            totalPay += PIZZAPRICE;
        }
        else{
            totalPay -= PIZZAPRICE;
        }
        totalPayTextField.setText(String.valueOf(totalPay));
    }//GEN-LAST:event_pizzaCheckBoxActionPerformed

    private void addOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderButtonActionPerformed
        String name = "Nama: " + customerNameField.getText() + "\n";
        String address = "Alamat: " + addressField.getText() + "\n";
        String phone = "Telp: " + phoneField.getText() + "\n";
        
        String data = name + address + phone + "=================\n";
        if(steakCheckBox.isSelected()){
            data += "   - " + steakCheckBox.getText() + "\n";
        }
        if(sphagetiCheckBox.isSelected()){
            data += "   - " + sphagetiCheckBox.getText() + "\n";
        }
        if(pizzaCheckBox.isSelected()){
            data += "   - " + pizzaCheckBox.getText() + "\n";
        }
        data += "=================\n" + "Total Bayar:\n   RP. " + totalPay;
        
        dataTextArea.setText(data);
    }//GEN-LAST:event_addOrderButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        Customer customer = new Customer(customerNameField.getText(), addressField.getText(), phoneField.getText());
        ArrayList<Menu> menus = new ArrayList<>();
        if(steakCheckBox.isSelected()){
            menus.add(new Menu(steakCheckBox.getText(), STEAKPRICE));
        }
        if(sphagetiCheckBox.isSelected()){
            menus.add(new Menu(sphagetiCheckBox.getText(), SPHAGETIPRICE));
        }
        if(pizzaCheckBox.isSelected()){
            menus.add(new Menu(pizzaCheckBox.getText(), PIZZAPRICE));
        }
        Menu[] cast = new Menu[menus.size()];
        Order order = new Order(customer, menus.toArray(cast), Integer.parseInt(totalPayTextField.getText()));
        ArrayList<Order> dataOrders = loadData();
        try{
            FileOutputStream fileStream = new FileOutputStream("src/Data Penjualan.ser");
            ObjectOutputStream objectStream = new ObjectOutputStream(fileStream);
            if(dataOrders != null){
                for(Order data : dataOrders){
                    objectStream.writeObject(data);
                }
            }
            objectStream.writeObject(order);
            objectStream.close();
            fileStream.close();
            JOptionPane.showMessageDialog(this, "Data Berhasi Disimpan");
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private ArrayList<Order> loadData(){
        ArrayList<Order> dataOrders = new ArrayList<>();
        try{
            FileInputStream fileStream = new FileInputStream("src/Data Penjualan.ser");
            ObjectInputStream objectStream = new ObjectInputStream(fileStream);
            try{
                while(true){
                    dataOrders.add((Order)objectStream.readObject());
                    
                }
            }
            catch(EOFException endOfFileEx){
                objectStream.close();
                fileStream.close();
                
                return dataOrders;
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return null;
    }
    
    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        String data = "";
        ArrayList<Order> ordersData = loadData();
        if(ordersData == null){
            return;
        }
        for(Order dataOrder : ordersData){
            data += getDataOrderText(dataOrder) + "\n=================\n";
        }
        dataTextArea.setText(data);
    }//GEN-LAST:event_loadButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        try{
            FileOutputStream os = new FileOutputStream("src/Data Penjualan.ser");
            os.close();
            dataTextArea.setText("");
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_resetButtonActionPerformed

    public String getDataOrderText(Order order){
        String name = "Nama: " + order.getCustomer().getName() + "\n";
        String address = "Alamat: " + order.getCustomer().getAddress() + "\n";
        String phone = "Telp: " + order.getCustomer().getTelephone() + "\n";
        
        String data = name + address + phone + "=================\n";
        for(int i=0;i<order.getMenus().length;i++){
            data += "   - " + order.getMenus()[i].getName() + "\n";
        }
        data += "=================\n" + "Total Bayar:\n   RP. " + order.getTotal();
        return data;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrderButton;
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JPanel dataPenjualanPanel;
    private javax.swing.JTextArea dataTextArea;
    private javax.swing.JPanel foodMenuPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JButton loadButton;
    private javax.swing.JTextField phoneField;
    private javax.swing.JCheckBox pizzaCheckBox;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JCheckBox sphagetiCheckBox;
    private javax.swing.JCheckBox steakCheckBox;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel totalPanel;
    private javax.swing.JLabel totalPayLabel;
    private javax.swing.JTextField totalPayTextField;
    // End of variables declaration//GEN-END:variables
}
